### PR TITLE
Tests

### LINKED ISSUE #1: Write integration tests
I'm not good at integration testing and better that someone else does it.

## What's needed

- Pick a integration testing tool, the smaller and faster it is the better
- write lots of tests and achieve 100% coverage (you can check coverage locally)
- pull request the tests

## What you shouldn't do

- don't hardcore wallet addresses in tests. Either use env variables or create a wallet with random key using ethers.js. PM [me](https://t.me/talentless_guy) to add secrets in a GitHub env
- don't use any commonjs transpilators. Tests must be pure ESM as well as the source. CommonJS fallback that is present rn will be soon removed, since Next.js got ESM externals feature in the 11.0.2-canary.10 release, so please be aware of that.
- don't use jest (bc it's too heavy and contains too much unnecessary stuff)

## What to consider

- please keep the formatting correct and fix all lint errors you get. It's already handled by husky, but still
- would be awesome if the tool you choose has a GitHub app, so it can report coverage change on commit / PR

## Some test examples 

Not the full list, just to give an idea which tests are required:

- wallet options
  - should work without constructor
  - should work without `appId`
  - should support different chains (with `networkId`)
  - should support passed wallet providers
  - should use initial data while the hook is loading
 - hook properties
   -  `isWalletSelected`
     - false by default
     - should set `isWalletSelected` to true after successful wallet connect
 
thanks to whoever writes the tests, I appreciate it a lot :)

### PR DESCRIPTION
**Pull request by Clish254**
fixes #1 
This is a draft pr. Currently having trouble getting tests to work with ganache web3 provider. I keep getting an error "Expected private key to be an Uint8Array"

### CODE REVIEW

**Comment by talentlessguy** [comment]
1) please convert to a draft PR
2) why do you use react-scripts? I don't think they're required
3) why `jest-environment-jsdom` is there? as mentioned in the PR, Jest is not allowed to be used.

**Comment by Clish254** [comment]
I didn't find a way to run react testing library without react scripts. Will remove `jest-environment-jsdom', I was using it with mocha before to test some example components but I forgot to remove it.

**Comment by talentlessguy** [comment]
@Clish254 did you try just by running `mocha test.ts`? or it doesn't work this way

**Comment by Clish254** [comment]
Mocha wasn't working well with ESM

**Comment by talentlessguy** [comment]
also could you please move tests to root instead? don't want to have them in src folder, since src contains the source

i mean `src/__tests__` to `src/tests`

**Comment by Clish254** [comment]
Okay

**Comment by talentlessguy** [comment]
> Mocha wasn't working well with ESM

see this: https://mochajs.org/#nodejs-native-esm-support

try using flags like here: https://github.com/tinyhttp/tinyws/blob/bf1a7dafa3a9be0089ab6c5b64131d8b50a2a6f0/package.json#L16

**Comment by Clish254** [comment]
Okay, I found a solution for the mocha issue [here](https://github.com/TypeStrong/ts-node/discussions/1268), but now i'm getting a new error "Cannot find module react/jsx-runtime".

**Comment by talentlessguy** [comment]
ill checkout your PR locally and will try to fix this error

**Comment by talentlessguy** [comment]
hey, I've tried moving to uvu + esbuild-node-loader + undom (but have the same test syntax / suite), now I have this:

```ts
> node --experimental-specifier-resolution=node --experimental-loader ts-node/esm node_modules/uvu/bin.js tests

(node:52235) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Cannot read property '__reactEvents$40dnlm9iw2' of undefined
```

idk what to do here tbh... by the way those are unit tests not integration ones but i'm ok with that

just in case - maybe u could give cypress a try instead? it should be easier to test with

**Comment by Clish254** [comment]
> hey, I've tried moving to uvu + esbuild-node-loader + undom (but have the same test syntax / suite), now I have this:
> 
> ```ts
> > node --experimental-specifier-resolution=node --experimental-loader ts-node/esm node_modules/uvu/bin.js tests
> 
> (node:52235) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> TypeError: Cannot read property '__reactEvents$40dnlm9iw2' of undefined
> ```
> 
> idk what to do here tbh... by the way those are unit tests not integration ones but i'm ok with that
> 
> just in case - maybe u could give cypress a try instead? it should be easier to test with

Okay, I was actually looking into cypress.

**Comment by talentlessguy** [comment]
@Clish254 any updates?

**Pull request closed without merging**
